global:
  message: Welcome to global Mircoservices Environment!
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
  endpoint:
    health:
      show-details: always
