spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/customer_master?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
